name:                Day9
version:             0.1.0.0
github:              "btrzcinski/Day9"
license:             BSD3
author:              "Barnett Trzcinski"
maintainer:          "btrzcinski@gmail.com"
copyright:           "2021 Barnett Trzcinski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/btrzcinski/Day9#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers
- extra
- matrix

library:
  source-dirs: src

executables:
  Day9-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day9

tests:
  Day9-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day9
    - tasty
    - tasty-hunit
