name:                Day5
version:             0.1.0.0
github:              "btrzcinski/Day5"
license:             BSD3
author:              "Barnett Trzcinski"
maintainer:          "btrzcinski@gmail.com"
copyright:           "2021 Barnett Trzcinski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/btrzcinski/Day5#readme>

dependencies:
- base >= 4.7 && < 5
- split
- extra
- multiset

library:
  source-dirs: src

executables:
  Day5-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day5

tests:
  Day5-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day5
    - tasty
    - tasty-hunit

